#############################################################################
# Makefile for building: DCCConnect
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  DCCConnect.pro
# Template: app
# Command: /opt/qt5/qt5.5.1/bin/qmake -spec linux-arm-gnueabihf-g++ -o Makefile DCCConnect.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc
CXX           = arm-linux-gnueabihf-g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../intelFPGA/16.1/embedded/ip/altera/hps/altera_hps/hwlib/include -I../../intelFPGA/16.1/embedded/ip/altera/hps/altera_hps/hwlib/include/soc_cv_av -I/home/nathan/intelFPGA/16.1/embedded/ip/altera/hps/altera_hps/hwlib/include -I/home/nathan/intelFPGA/16.1/embedded/ip/altera/hps/altera_hps/hwlib/include/soc_cv_av -I/opt/qt5/qt5.5.1-intel-soc/include -I/opt/qt5/qt5.5.1-intel-soc/include/QtCore -I. -I/opt/qt5/qt5.5.1/mkspecs/linux-arm-gnueabihf-g++
QMAKE         = /opt/qt5/qt5.5.1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = DCCConnect1.0.0
DISTDIR = /home/terasic/Documents/HELEN_RAD_MCU/.tmp/DCCConnect1.0.0
LINK          = arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Qt-5.5.1/lib
LIBS          = $(SUBLIBS) -L/opt/qt5/qt5.5.1-intel-soc/lib -lQt5Core -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		fpga.cpp \
		hps.cpp \
		writer.cpp 
OBJECTS       = main.o \
		fpga.o \
		hps.o \
		writer.o
DIST          = /opt/qt5/qt5.5.1/mkspecs/features/spec_pre.prf \
		/opt/qt5/qt5.5.1/mkspecs/common/unix.conf \
		/opt/qt5/qt5.5.1/mkspecs/common/linux.conf \
		/opt/qt5/qt5.5.1/mkspecs/common/sanitize.conf \
		/opt/qt5/qt5.5.1/mkspecs/common/gcc-base.conf \
		/opt/qt5/qt5.5.1/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5/qt5.5.1/mkspecs/common/g++-base.conf \
		/opt/qt5/qt5.5.1/mkspecs/common/g++-unix.conf \
		/opt/qt5/qt5.5.1/mkspecs/qconfig.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/features/qt_functions.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/qt_config.prf \
		/opt/qt5/qt5.5.1/mkspecs/linux-arm-gnueabihf-g++/qmake.conf \
		/opt/qt5/qt5.5.1/mkspecs/features/spec_post.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/exclusive_builds.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/default_pre.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/resolve_config.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/default_post.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/c++11.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/warn_on.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/qt.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/resources.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/moc.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/unix/thread.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/testcase_targets.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/exceptions.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/yacc.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/lex.prf \
		DCCConnect.pro fpga.h \
		hps.h \
		writer.h main.cpp \
		fpga.cpp \
		hps.cpp \
		writer.cpp
QMAKE_TARGET  = DCCConnect
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = DCCConnect


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DCCConnect.pro /opt/qt5/qt5.5.1/mkspecs/linux-arm-gnueabihf-g++/qmake.conf /opt/qt5/qt5.5.1/mkspecs/features/spec_pre.prf \
		/opt/qt5/qt5.5.1/mkspecs/common/unix.conf \
		/opt/qt5/qt5.5.1/mkspecs/common/linux.conf \
		/opt/qt5/qt5.5.1/mkspecs/common/sanitize.conf \
		/opt/qt5/qt5.5.1/mkspecs/common/gcc-base.conf \
		/opt/qt5/qt5.5.1/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5/qt5.5.1/mkspecs/common/g++-base.conf \
		/opt/qt5/qt5.5.1/mkspecs/common/g++-unix.conf \
		/opt/qt5/qt5.5.1/mkspecs/qconfig.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5/qt5.5.1/mkspecs/features/qt_functions.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/qt_config.prf \
		/opt/qt5/qt5.5.1/mkspecs/linux-arm-gnueabihf-g++/qmake.conf \
		/opt/qt5/qt5.5.1/mkspecs/features/spec_post.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/exclusive_builds.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/default_pre.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/resolve_config.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/default_post.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/c++11.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/warn_on.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/qt.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/resources.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/moc.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/unix/thread.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/testcase_targets.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/exceptions.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/yacc.prf \
		/opt/qt5/qt5.5.1/mkspecs/features/lex.prf \
		DCCConnect.pro \
		/opt/qt5/qt5.5.1-intel-soc/lib/libQt5Core.prl
	$(QMAKE) -spec linux-arm-gnueabihf-g++ -o Makefile DCCConnect.pro
/opt/qt5/qt5.5.1/mkspecs/features/spec_pre.prf:
/opt/qt5/qt5.5.1/mkspecs/common/unix.conf:
/opt/qt5/qt5.5.1/mkspecs/common/linux.conf:
/opt/qt5/qt5.5.1/mkspecs/common/sanitize.conf:
/opt/qt5/qt5.5.1/mkspecs/common/gcc-base.conf:
/opt/qt5/qt5.5.1/mkspecs/common/gcc-base-unix.conf:
/opt/qt5/qt5.5.1/mkspecs/common/g++-base.conf:
/opt/qt5/qt5.5.1/mkspecs/common/g++-unix.conf:
/opt/qt5/qt5.5.1/mkspecs/qconfig.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_core.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_gui.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_network.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_qml.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_sql.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_svg.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_xml.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt5/qt5.5.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt5/qt5.5.1/mkspecs/features/qt_functions.prf:
/opt/qt5/qt5.5.1/mkspecs/features/qt_config.prf:
/opt/qt5/qt5.5.1/mkspecs/linux-arm-gnueabihf-g++/qmake.conf:
/opt/qt5/qt5.5.1/mkspecs/features/spec_post.prf:
/opt/qt5/qt5.5.1/mkspecs/features/exclusive_builds.prf:
/opt/qt5/qt5.5.1/mkspecs/features/default_pre.prf:
/opt/qt5/qt5.5.1/mkspecs/features/resolve_config.prf:
/opt/qt5/qt5.5.1/mkspecs/features/default_post.prf:
/opt/qt5/qt5.5.1/mkspecs/features/c++11.prf:
/opt/qt5/qt5.5.1/mkspecs/features/warn_on.prf:
/opt/qt5/qt5.5.1/mkspecs/features/qt.prf:
/opt/qt5/qt5.5.1/mkspecs/features/resources.prf:
/opt/qt5/qt5.5.1/mkspecs/features/moc.prf:
/opt/qt5/qt5.5.1/mkspecs/features/unix/thread.prf:
/opt/qt5/qt5.5.1/mkspecs/features/testcase_targets.prf:
/opt/qt5/qt5.5.1/mkspecs/features/exceptions.prf:
/opt/qt5/qt5.5.1/mkspecs/features/yacc.prf:
/opt/qt5/qt5.5.1/mkspecs/features/lex.prf:
DCCConnect.pro:
/opt/qt5/qt5.5.1-intel-soc/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-arm-gnueabihf-g++ -o Makefile DCCConnect.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents fpga.h hps.h writer.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp fpga.cpp hps.cpp writer.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp writer.h \
		fpga.h \
		hps.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/QCoreApplication \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcoreapplication.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qglobal.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qconfig.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qfeatures.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qsystemdetection.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qprocessordetection.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcompilerdetection.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qtypeinfo.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qtypetraits.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qsysinfo.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qlogging.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qflags.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qbasicatomic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qgenericatomic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_gcc.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_msvc.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_armv7.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_armv6.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_armv5.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_ia64.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_mips.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_x86.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_unix.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qglobalstatic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qmutex.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qnumeric.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstring.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qchar.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qbytearray.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qrefcount.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qnamespace.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qarraydata.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstringbuilder.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobject.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobjectdefs.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qlist.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qalgorithms.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qiterator.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qbytearraylist.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstringlist.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qregexp.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstringmatcher.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcoreevent.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qscopedpointer.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qmetatype.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qvarlengtharray.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcontainerfwd.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qisenum.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobject_impl.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qeventloop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

fpga.o: fpga.cpp fpga.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/QDebug \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qdebug.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qalgorithms.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qglobal.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qconfig.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qfeatures.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qsystemdetection.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qprocessordetection.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcompilerdetection.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qtypeinfo.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qtypetraits.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qsysinfo.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qlogging.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qflags.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qbasicatomic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qgenericatomic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_gcc.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_msvc.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_armv7.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_armv6.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_armv5.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_ia64.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_mips.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_x86.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_unix.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qglobalstatic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qmutex.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qnumeric.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qhash.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qchar.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qiterator.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qlist.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qrefcount.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qarraydata.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qbytearraylist.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qbytearray.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qnamespace.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstring.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstringbuilder.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstringlist.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qregexp.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstringmatcher.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qpair.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qmap.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qtextstream.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qiodevice.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobject.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobjectdefs.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcoreevent.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qscopedpointer.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qmetatype.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qvarlengtharray.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcontainerfwd.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qisenum.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobject_impl.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qlocale.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qvariant.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qshareddata.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qvector.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qpoint.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qset.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcontiguouscache.h \
		../../intelFPGA/16.1/embedded/ip/altera/hps/altera_hps/hwlib/include/soc_cv_av/socal/socal.h \
		../../intelFPGA/16.1/embedded/ip/altera/hps/altera_hps/hwlib/include/soc_cv_av/socal/hps.h \
		../../intelFPGA/16.1/embedded/ip/altera/hps/altera_hps/hwlib/include/soc_cv_av/socal/alt_gpio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fpga.o fpga.cpp

hps.o: hps.cpp /opt/qt5/qt5.5.1-intel-soc/include/QtCore/QDebug \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qdebug.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qalgorithms.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qglobal.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qconfig.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qfeatures.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qsystemdetection.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qprocessordetection.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcompilerdetection.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qtypeinfo.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qtypetraits.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qsysinfo.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qlogging.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qflags.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qbasicatomic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qgenericatomic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_gcc.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_msvc.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_armv7.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_armv6.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_armv5.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_ia64.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_mips.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_x86.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_unix.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qglobalstatic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qmutex.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qnumeric.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qhash.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qchar.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qiterator.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qlist.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qrefcount.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qarraydata.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qbytearraylist.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qbytearray.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qnamespace.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstring.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstringbuilder.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstringlist.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qregexp.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstringmatcher.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qpair.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qmap.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qtextstream.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qiodevice.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobject.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobjectdefs.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcoreevent.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qscopedpointer.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qmetatype.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qvarlengtharray.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcontainerfwd.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qisenum.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobject_impl.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qlocale.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qvariant.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qshareddata.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qvector.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qpoint.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qset.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcontiguouscache.h \
		hps.h \
		../../intelFPGA/16.1/embedded/ip/altera/hps/altera_hps/hwlib/include/soc_cv_av/socal/socal.h \
		../../intelFPGA/16.1/embedded/ip/altera/hps/altera_hps/hwlib/include/soc_cv_av/socal/hps.h \
		../../intelFPGA/16.1/embedded/ip/altera/hps/altera_hps/hwlib/include/soc_cv_av/socal/alt_gpio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hps.o hps.cpp

writer.o: writer.cpp writer.h \
		fpga.h \
		hps.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/QDebug \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qdebug.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qalgorithms.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qglobal.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qconfig.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qfeatures.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qsystemdetection.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qprocessordetection.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcompilerdetection.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qtypeinfo.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qtypetraits.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qsysinfo.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qlogging.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qflags.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qbasicatomic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qgenericatomic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_gcc.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_msvc.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_armv7.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_armv6.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_armv5.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_ia64.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_mips.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_x86.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qatomic_unix.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qglobalstatic.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qmutex.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qnumeric.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qhash.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qchar.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qiterator.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qlist.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qrefcount.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qarraydata.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qbytearraylist.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qbytearray.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qnamespace.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstring.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstringbuilder.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstringlist.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qregexp.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qstringmatcher.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qpair.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qmap.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qtextstream.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qiodevice.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobject.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobjectdefs.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcoreevent.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qscopedpointer.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qmetatype.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qvarlengtharray.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcontainerfwd.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qisenum.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qobject_impl.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qlocale.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qvariant.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qshareddata.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qvector.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qpoint.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qset.h \
		/opt/qt5/qt5.5.1-intel-soc/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o writer.o writer.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

